### ISSUE TITLE
Error in script when trying to install.

### ISSUE THREAD

**Issue by MarisaKirisame-ze** [aubymori/YouTubePatchCollection#2]
H-H-Hewwo. This T-Tampewmonkey scwipt isn't w-wowking fow me. It says an error when *notices buldge* I try t-to instaww it. >w< Pwease fix it, thanks.

Translation:
Hello. This Tampermonkey script isn't working for me. It says an error when I try to install it. Please fix it, thanks.

**Comment by aubymori** [comment]
1. Never speak like that again or I'm blocking you
2. Could you be more specific? A screenshot of the error would help

**Comment by aubymori** [comment]
I see the issue, actually.
