### ISSUE TITLE
YouTube Studio Bug

### ISSUE THREAD

**Issue by Yacine-Book** [aubymori/YouTubePatchCollection#7]
The YT Studio Patch Collection userscript no-longer changes the YT Studio icons, can you please fix it?

**Comment by Yacine-Book** [comment]
Come on aubymori, fix it!

**Comment by Yacine-Book** [comment]
Come on, WHAT'S TAKING SO LONG?! JUST FIX IT!

**Comment by aubymori** [comment]
Seems like they changed something, but I will not be fixing this, I gave up on anything Polymer-related. Sorry.
